# Generated by Django 5.2.5 on 2025-08-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='board',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='board',
            name='renewal_by',
        ),
        migrations.AddField(
            model_name='board',
            name='createdby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='board',
            name='renewalby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
