# Generated by Django 5.2.5 on 2025-09-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0003_alter_board_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='next_renewal_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='renewal_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
